apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namePrefix: prod-
namespace: upskilling-helm-prod

# Injects the values file directly into the inherited helm chart compilation
helmGlobals:
  valueFiles:
    - values.yaml