apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-rollouts
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/argoproj/argo-rollouts.git'
    path: manifests/cluster-install
    targetRevision: v1.7.2
    cloneDepth: 1 # ◄── Forces a shallow clone (takes less than 1 second!)
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argo-rollouts
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true