apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-guestbook
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/sumith0810/devops-upskilling-gitops.git' # Replace with your repo
    targetRevision: HEAD
    path: apps/guestbook/envs/dev
  destination:
    server: 'https://kubernetes.default.svc' # Local cluster
    namespace: upskilling-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true