apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-helm-apache
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://stefanprodan.github.io/podinfo'
    chart: podinfo
    targetRevision: 6.7.0
    helm:
      # Injecting the values directly inline completely bypasses any Git caching bugs!
      values: |
        replicaCount: 1
        ui:
          color: "#34577c"
          message: "Hello from DevOps Upskilling!"
        service:
          type: ClusterIP
          nodePort: null
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 32Mi
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: upskilling-helm-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true