apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-helm-apache
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: 'https://stefanprodan.github.io/podinfo' # A clean, generic test chart registry
      chart: podinfo
      targetRevision: 6.x.x
      helm:
        valueFiles:
          - $values/helm/apache/envs/dev-values.yaml
    - repoURL: 'https://github.com/sumith0810/devops-upskilling-gitops.git'
      targetRevision: HEAD
      ref: values
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: upskilling-helm-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true