apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://bitnami.github.io/sealed-secrets'
    chart: sealed-secrets
    targetRevision: 2.15.0
    helm:
      values: |
        rbac:
          serviceProxier:
            bind: false
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: sealed-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true