apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://bitnami.github.io/sealed-secrets'
    chart: sealed-secrets
    targetRevision: 2.15.0
    helm:
      values: |
        namespace: sealed-secrets
        rbac:
          serviceProxier:
            create: false
            bind: false
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: sealed-secrets
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/strategy/rollingUpdate/maxSurge
        - /spec/template/spec/containers/0/resources
      jqPathExpressions:
        - .metadata.annotations["autopilot.gke.io/resource-adjustment"]
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true