apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Still pointing to that exact same shared base layer
resources:
  - ../../base

namePrefix: prod-
namespace: upskilling-prod
# We will apply a patch to change the replica count just for Production
patches:
  - target:
      kind: Deployment
      name: guestbook-ui
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
