replicaCount: 1

# Using the chart's native image hosted on GitHub Container Registry (bypasses Docker Hub blocks)
image:
  repository: ghcr.io/stefanprodan/podinfo
  tag: 6.7.0

service:
  type: ClusterIP
  port: 9898 # Podinfo defaults to running on port 9898

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi