# Use the official AWS ECR Mirror for Bitnami to bypass the Docker Hub corporate block
image:
  registry: public.ecr.aws
  repository: bitnami/apache
  tag: 2.4.63-debian-12-r0  # Pinned to a verified, stable tag on AWS ECR

# Required by Bitnami charts when you move away from DockerHub
global:
  security:
    allowInsecureImages: true

replicaCount: 1

service:
  type: ClusterIP
  port: 80

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi