apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namePrefix: dev-
namespace: upskilling-helm-dev

# Correct way to bind local values files to the inherited base chart in Kustomize
helmCharts:
  - name: podinfo
    releaseName: podinfo
    valuesFile: values.yaml