---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: database-credentials
  namespace: upskilling-helm-dev
spec:
  encryptedData:
    DB_PASSWORD: AgBTnDTd5MV1SlR4py1ezrxSCvO+GmIrSD3ui8Zl5VYDHc3m268vPB3MvVWmWsnxnwOKXNos21rudkDqosdosRYBDoXuFnwLt3Wze17WqPpiGZtAn/YjNHTSLLVTNaZg3OgFU78m/a3/EUvUNfFxgXSEFA+WKkevMW2cdrnboqz9NImvCGAChxWFoyQcOjZ3uJnygBKbkfTr3PcBU995maR9co529oW6cozhs9ijg7yCsJkZi9AOcgz8hQyQPRE4QWODOocZQ167/c1ihp4x6Cy2uVLSy88Jk1/eRvRFiy/glpUshFhPx/jrsj7Sb9CZ7ZM68HamsWMFEzZiCuE4mTcI0sjxGtAJIPO/Z/OmTFSkx2a4QObJtrFXdUqndUzITeOwuIITcp/00iw37obnNKGzcKb61xYItjsDVmFIWDlMOV2mwoZ9tKhz5G35/qO9DJIq/44GK3BFpquvFuTXIdXlfvokFBDE7/I5hWrhGNk0PJSXVKeYOF+ZasSWp9J2rbhsqgYz0g7U+iFdSzqX+oopYXA0MmHBq+J1k9/yj60wMBtNZsykI0zkwZ72AvGXqQgarwAH/LHn2dZCRRqH4QLAb2fhu2mWeJZf3LRqaDhQW4em2IHAOQ0hJkzYMlVGuBjj5KZ3LixfLXWKVBEbgElkgiI2JisDYkw5r2Hi5g+WXuNar1EMaYZVxoiVFdRSDrHdIsrqG5RcZ9erB1YSpA72k5Qr9GqN0Q==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: database-credentials
      namespace: upskilling-helm-dev
