---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: database-credentials
  namespace: upskilling-helm-dev
spec:
  encryptedData:
    DB_PASSWORD: AgCqrVNvaGJX6jeeoxNZ+wTqPAh51W0knDnWc2EzZkuX+8gxFQasd6nhXo/INkbJpXJca/idksDBy3rYLSJg+KsTzeay054Ej8sXgO+sdlmUimk50Wrf+iRGj8vUGb0vvsT5Tob6yn94RhKnqbuVUjFov9TkvTDL9l2a85ByU+GGML2hbYpvCaRWkWrLEUHRMWwmgx0lKbURHjvVY4QCNp6m0RHtko3NhvCeHKXmYCFhwEKeEPZrOqDDDIYHADeehk0SkyAxPV60IFiUoCAbQRr/Z8yyhLmp8vk44RRHFAaMxvni035mRQRFAAtvnPjWPPZy919mVaN3LmuKFoEHbIMPsnevp0RYdFX+KsKRuxnro01mgtO0zT8v3mGfSxbQZUGfMmlF81sVf+LaDJfaJSXpoXpFUx+0RBRNdMPzoP4+FDlsG+Ld6TgXuOmLn7rGV1Kk2CJXYdHUkRisZoy/ILtZ/owI62/hj37TLqWZ50xZrrRzL09OiT9NWoF8dFkg6xwBq0donyZv0OG9O/dVDy0n1PulrgcOTKV2z0r70HD4T/CkHguMLpnKblF0J9fEfWa8Bt+sGKbljJDin7zGWvcGTZN6J5sIfzO3j6H9LiO/Im2LvZajpvM0tzlWrDEnQxP1mO/9+2RRc/vUJbyca9Vq7dpPp9pypLrKyuHVTNKSXp//3gYOS2nv1Soi/5yYsdYkQDQB6fuDdrYqqvn6KTX5wviU
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: database-credentials
      namespace: upskilling-helm-dev
