---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: database-credentials
  namespace: upskilling-helm-dev
spec:
  encryptedData:
    DB_PASSWORD: AgCd7NC8iyQ6mkLXdvzopG72BYr5F7bnc4nSYo8aKk2b36G4PyoWy7TTbn8RrnPozra3Um4sDEDE821mu6SYi+OKJRcR1qxSF2rZpmte8JKUHeGFgFwd8hkjk41LxrYFHDjFVtgEojJlm4Sz2a1E5Re7WvN6tCWTCzHu09N6Q4g3oqq8ZPVHtyFHYVU/MP+/0o5e137XUGBhzNPMugLf1wfOovG52ZFtaQPKf373ZkY0QL/YyaieDmrO1wEH0J1dzEw3a67QnARkszkMNXiXVfu4FE9VCE+12uOsMr1asO2xk3rMOWSofNs4S8o041FCnii8iC5ARKsdDYaYC/Xj2tbKN7JHLsfJ5n4wh3n06OytTvsnZTHYLUuD4kJ1gZ6w6VHuhWR9K99lDWj75+ZAAVeO40+8SunnZ9nHw1SWqiNA9XCKekK3KAge6RyW7StW4GVjdZjR8VhZGodluJTI0jzF4ZJYnrY2UcmOHdAqDbB1+WG3TaDsJhvjblX5TOG/pkg9E/h91YwJkjRp49SaAhK/pxb0A3LTwBG/nFM1AhV9uLz2PkkOKaX+2bEE6ZDXcfSHhBu0ZP8KxzudQdA1lx/wQFGP4yJAZwKribuRqqg2FVhjj3qIyPK4sdpaWtJmhJdVuvo+bS+kQdypCWoqJWDt84uWntoj56HYMZLEG7vQ8NHYch19aNBv/tyehKlrTkIFx2xSWXzLiauHGdpqgsMskTzTXrppKQ==
  template:
    metadata:
      name: database-credentials
      namespace: upskilling-helm-dev
    type: Opaque
