replicaCount: 1
ui:
  color: "#34577c"
  message: "Hello from Dev Helm-Kustomize!"
service:
  type: ClusterIP
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 10m
    memory: 32Mi# Last deployed by CI: dev-5ee7d181b5a0f426994a850308fd7dd0021245e5
