apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui
  namespace: upskilling-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      containers:
      - name: guestbook-ui
        image: docker.io/argoproj/guestbook:v1
        ports:
        - containerPort: 80